export const s = {
  page: {
    fontFamily: 'Inter, Segoe UI, Arial, sans-serif',
    minHeight: '100vh',
    background: '#f5f7fb',
    color: '#1f2937',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '14px 24px',
    background: '#fff',
    borderBottom: '1px solid #e5e7eb',
    marginBottom: 24,
  },
  h1: { margin: 0, fontSize: '1.25rem', fontWeight: 700 },
  h2: { marginTop: 0, marginBottom: 16, fontSize: '1rem', fontWeight: 600 },
  subtitle: { margin: '4px 0 0', color: '#6b7280', fontSize: '0.875rem' },
  content: { padding: '0 24px 40px' },
  layout: { display: 'grid', gap: 20 },
  card: {
    background: '#fff',
    borderRadius: 12,
    padding: 20,
    boxShadow: '0 2px 8px rgba(16,24,40,.06)',
  },
  formGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
    gap: 14,
  },
  label: { display: 'block', marginBottom: 6, fontWeight: 600, fontSize: '0.875rem' },
  input: {
    width: '100%',
    border: '1px solid #d1d5db',
    borderRadius: 8,
    padding: '9px 12px',
    boxSizing: 'border-box',
    fontSize: '0.9rem',
  },
  btn: {
    border: 0,
    background: '#2563eb',
    color: '#fff',
    padding: '10px 20px',
    borderRadius: 8,
    fontWeight: 600,
    cursor: 'pointer',
    fontSize: '0.875rem',
  },
  btnSecondary: {
    border: '1px solid #d1d5db',
    background: '#fff',
    color: '#374151',
    padding: '9px 16px',
    borderRadius: 8,
    cursor: 'pointer',
    fontWeight: 500,
    fontSize: '0.875rem',
  },
  btnGreen: {
    border: 0,
    background: '#16a34a',
    color: '#fff',
    padding: '9px 16px',
    borderRadius: 8,
    fontWeight: 600,
    cursor: 'pointer',
    fontSize: '0.875rem',
  },
  tableWrap: { overflowX: 'auto', marginTop: 12 },
  table: { width: '100%', borderCollapse: 'collapse', fontSize: '0.85rem' },
  th: {
    background: '#f9fafb',
    padding: '10px 12px',
    textAlign: 'left',
    fontWeight: 600,
    borderBottom: '2px solid #e5e7eb',
    whiteSpace: 'nowrap',
  },
  td: { padding: '9px 12px', borderBottom: '1px solid #f3f4f6', verticalAlign: 'top' },
  filterRow: { display: 'flex', gap: 12, marginBottom: 20, flexWrap: 'wrap', alignItems: 'center' },
  filterInput: {
    border: '1px solid #d1d5db',
    borderRadius: 8,
    padding: '9px 12px',
    fontSize: '0.875rem',
    background: '#fff',
  },
  sheet: { border: '1px solid #e5e7eb', borderRadius: 10, padding: 16, marginTop: 16 },
  sheetHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
    marginBottom: 8,
  },
  sheetTitle: { margin: 0, fontSize: '1rem', fontWeight: 600 },
  badge: {
    display: 'inline-block',
    background: '#eff6ff',
    color: '#1d4ed8',
    borderRadius: 20,
    padding: '2px 10px',
    fontSize: '0.78rem',
    fontWeight: 600,
    marginRight: 6,
  },
  loginPage: {
    minHeight: '100vh',
    display: 'grid',
    placeItems: 'center',
    background: '#f0f4ff',
  },
  loginCard: {
    width: '100%',
    maxWidth: '400px',
    background: '#fff',
    borderRadius: 14,
    padding: '36px 32px',
    boxShadow: '0 10px 30px rgba(0,0,0,.12)',
  },
  loginTitle: { margin: '0 0 6px', fontSize: '1.6rem', fontWeight: 700 },
  errorText: { color: '#dc2626', fontSize: '0.875rem', marginTop: 8 },
};
