// Design tokens — violet-indigo palette
// --accent       #5D52D1  deep violet, primary actions
// --accent-soft  #EDEAFF  light violet tint, badges, hover
// --bg           #F5F4FB  off-white with violet undertone
// --surface      #FFFFFF
// --text         #1B1A35  near-black with violet cast
// --muted        #7877A0  desaturated violet-gray
// --border       #E3E0F5  light violet border

export const C = {
  accent:      '#5D52D1',
  accentDark:  '#3B3180',
  accentSoft:  '#EDEAFF',
  accentMid:   '#8B82E4',
  bg:          '#F5F4FB',
  surface:     '#FFFFFF',
  text:        '#1B1A35',
  muted:       '#7877A0',
  border:      '#E3E0F5',
  borderDark:  '#CAC6EE',
  shadow:      'rgba(93, 82, 209, 0.07)',
  shadowMd:    'rgba(93, 82, 209, 0.12)',
  green:       '#16a34a',
  greenSoft:   '#dcfce7',
  greenText:   '#166534',
};

export const s = {
  page: {
    fontFamily: 'Inter, Segoe UI, Arial, sans-serif',
    minHeight: '100vh',
    background: C.bg,
    color: C.text,
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '13px 28px',
    background: C.surface,
    borderBottom: `1px solid ${C.border}`,
    marginBottom: 24,
    boxShadow: `0 1px 0 ${C.border}`,
  },
  h1: { margin: 0, fontSize: '1.2rem', fontWeight: 700, color: C.text, letterSpacing: '-0.01em' },
  h2: { marginTop: 0, marginBottom: 16, fontSize: '1rem', fontWeight: 600, color: C.text },
  subtitle: { margin: '3px 0 0', color: C.muted, fontSize: '0.82rem', fontWeight: 400 },
  content: { padding: '0 24px 40px' },
  layout: { display: 'grid', gap: 20 },
  card: {
    background: C.surface,
    borderRadius: 12,
    padding: 20,
    boxShadow: `0 1px 3px ${C.shadow}, 0 4px 12px ${C.shadow}`,
    border: `1px solid ${C.border}`,
  },
  formGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
    gap: 14,
  },
  label: {
    display: 'block',
    marginBottom: 5,
    fontWeight: 600,
    fontSize: '0.8rem',
    color: C.muted,
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
  },
  input: {
    width: '100%',
    border: `1.5px solid ${C.border}`,
    borderRadius: 8,
    padding: '8px 11px',
    boxSizing: 'border-box',
    fontSize: '0.875rem',
    background: C.bg,
    color: C.text,
    outline: 'none',
    transition: 'border-color 0.15s',
  },
  btn: {
    border: 0,
    background: C.accent,
    color: '#fff',
    padding: '9px 18px',
    borderRadius: 8,
    fontWeight: 600,
    cursor: 'pointer',
    fontSize: '0.875rem',
    letterSpacing: '0.01em',
  },
  btnSecondary: {
    border: `1.5px solid ${C.border}`,
    background: C.surface,
    color: C.accent,
    padding: '8px 14px',
    borderRadius: 8,
    cursor: 'pointer',
    fontWeight: 500,
    fontSize: '0.875rem',
  },
  btnGreen: {
    border: 0,
    background: C.green,
    color: '#fff',
    padding: '9px 16px',
    borderRadius: 8,
    fontWeight: 600,
    cursor: 'pointer',
    fontSize: '0.875rem',
  },
  tableWrap: { overflowX: 'auto', marginTop: 12 },
  table: { width: '100%', borderCollapse: 'collapse', fontSize: '0.85rem' },
  th: {
    background: C.accentSoft,
    padding: '10px 12px',
    textAlign: 'left',
    fontWeight: 600,
    fontSize: '0.75rem',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    color: C.accent,
    borderBottom: `2px solid ${C.border}`,
    whiteSpace: 'nowrap',
  },
  td: {
    padding: '9px 12px',
    borderBottom: `1px solid ${C.border}`,
    verticalAlign: 'top',
    color: C.text,
  },
  filterRow: { display: 'flex', gap: 12, marginBottom: 20, flexWrap: 'wrap', alignItems: 'center' },
  filterInput: {
    border: `1.5px solid ${C.border}`,
    borderRadius: 8,
    padding: '8px 11px',
    fontSize: '0.875rem',
    background: C.surface,
    color: C.text,
  },
  sheet: {
    border: `1px solid ${C.border}`,
    borderRadius: 12,
    padding: 16,
    marginTop: 14,
    background: C.surface,
    boxShadow: `0 1px 4px ${C.shadow}`,
  },
  sheetHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
    marginBottom: 8,
  },
  sheetTitle: { margin: 0, fontSize: '0.95rem', fontWeight: 700, color: C.text, letterSpacing: '-0.01em' },
  badge: {
    display: 'inline-block',
    background: C.accentSoft,
    color: C.accent,
    borderRadius: 20,
    padding: '2px 9px',
    fontSize: '0.75rem',
    fontWeight: 600,
    marginRight: 5,
  },
  loginPage: {
    minHeight: '100vh',
    display: 'grid',
    placeItems: 'center',
    background: `linear-gradient(145deg, ${C.accentSoft} 0%, ${C.bg} 50%, #fff 100%)`,
  },
  loginCard: {
    width: '100%',
    maxWidth: '400px',
    background: C.surface,
    borderRadius: 16,
    padding: '36px 32px',
    boxShadow: `0 8px 40px ${C.shadowMd}`,
    border: `1px solid ${C.border}`,
  },
  loginTitle: { margin: '0 0 6px', fontSize: '1.5rem', fontWeight: 700, color: C.text, letterSpacing: '-0.02em' },
  errorText: { color: '#dc2626', fontSize: '0.875rem', marginTop: 8 },
};
